QuantaMesh 3000 Series T3048-LY2R - Form Factor: 1U height and 15.5 inches rack mountable - Port Configuration: 48 1/10GbE SFP/SFP+ and 4 40GbE QSFP+ - Management ports: 1 RJ-45 console port and 1 out-of-band 10/100/1000-Mbps management port - Power Supply: Dual high efficiency redundant, hot swappable power supplies

diff --git a/components/all/platform-config/powerpc-quanta-ly2r-r0/src/sbin/sfp-power-enable b/components/all/platform-config/powerpc-quanta-ly2r-r0/src/sbin/sfp-power-enable
--- a/components/all/platform-config/powerpc-quanta-ly2r-r0/src/sbin/sfp-power-enable
+++ b/components/all/platform-config/powerpc-quanta-ly2r-r0/src/sbin/sfp-power-enable
@@ -1,45 +1,52 @@
+#!/bin/sh
 ############################################################
 # <bsn.cl fy=2013 v=onl>
-#
-#        Copyright 2013, 2014 Big Switch Networks, Inc.
-#
+# 
+#        Copyright 2013, 2014 Big Switch Networks, Inc.       
+# 
 # Licensed under the Eclipse Public License, Version 1.0 (the
 # "License"); you may not use this file except in compliance
 # with the License. You may obtain a copy of the License at
-#
+# 
 #        http://www.eclipse.org/legal/epl-v10.html
-#
+# 
 # Unless required by applicable law or agreed to in writing,
 # software distributed under the License is distributed on an
 # "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 # either express or implied. See the License for the specific
 # language governing permissions and limitations under the
 # License.
-#
+# 
 # </bsn.cl>
 ############################################################
 #
-# These are the platforms to include in this installer build.
+# Platform: Quanta LY2R
 #
 ############################################################
-INSTALLER_PLATFORMS :=  powerpc-as4600-54t \
-			powerpc-as5600-52x \
-			powerpc-as5610-52x \
-			powerpc-as5710-54x-r0a \
-			powerpc-as5710-54x-r0b \
-			powerpc-as6700-32x-r0 \
-			powerpc-as6700-32x-r0b \
-			powerpc-quanta-lb9a-r0 \
-			powerpc-quanta-lb9-r0 \
-			powerpc-quanta-ly2-r0 \
-			powerpc-quanta-ly2r-r0 \
-			powerpc-quanta-ly6-p2020-r0 \
-			powerpc-quanta-ly6-p2041-r0 \
-			powerpc-dni-7448-r0
 
+cur_dir=$(dirname $0)
+if [ -x $cur_dir/functions ]; then
+	. $cur_dir/functions
+else
+	echo "$cur_dir/functions not found"
+	exit 1
+fi
 
+# Enable SFP module power
+# pca9555_24p10 ~ pca9555_24p13, pca9555_25p10 ~ pca9555_25p13
+#   are sfp power, 8 ports per pin
+# pca9555_25p14 is qsfp power
+pca9555_24=$(gpio_find 24)
+pca9555_24p10=$(($pca9555_24 + $pca953x_p10))
+pca9555_24p13=$(($pca9555_24 + $pca953x_p13))
+pca9555_25=$(gpio_find 25)
+pca9555_25p10=$(($pca9555_25 + $pca953x_p10))
+pca9555_25p14=$(($pca9555_25 + $pca953x_p14))
 
+for i in `seq $pca9555_24p10 $pca9555_24p13`; do
+	gpio_set $i 0
+done
 
-
-
-
+for i in `seq $pca9555_25p10 $pca9555_25p14`; do
+	gpio_set $i 0
+done
